# Generated by Django 5.2.5 on 2025-09-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='place_name',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
