# Generated by Django 5.2.5 on 2025-09-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_servicecenter_place_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='location',
            field=models.JSONField(null=True),
        ),
    ]
