# Generated by Django 5.2.5 on 2025-09-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_servicecenter_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='location',
            field=models.JSONField(blank=True, help_text="Store coordinates as {'lat': value, 'lng': value}", null=True),
        ),
    ]
