# Generated by Django 5.2.5 on 2025-09-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_servicecenter_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
