# Generated by Django 5.2.5 on 2025-09-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_servicecenter_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecenter',
            old_name='location',
            new_name='locations',
        ),
    ]
