# Generated by Django 5.2.5 on 2025-09-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_location_servicecenter_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecenter',
            name='locations',
        ),
    ]
