# Generated by Django 5.2.5 on 2025-09-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_servicecenter_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
