# Generated by Django 5.2.5 on 2025-09-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_servicecenter_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
