# Generated by Django 5.2.5 on 2025-09-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_emergencyrequest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecenter',
            name='place_name',
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='location',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='location',
            field=models.CharField(null=True),
        ),
    ]
