# Generated by Django 5.2.5 on 2025-09-28 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_servicecenter_place_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.servicecenter'),
        ),
    ]
