# Generated by Django 5.2.5 on 2025-09-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_emergencyrequest_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
